[[block]]
name = "sales"

  [[block.dimensions]]
  name = "product"
  sql = "product"
  data_type = "string"

  [[block.dimensions]]
  name = "category"
  sql = "category"
  data_type = "string"

  [[block.dimensions]]
  name = "sale_date"
  sql = "sale_date"
  data_type = "date"

  [[block.measures]]
  name = "total_quantity"
  sql = "sum(quantity)"

  [[block.measures]]
  name = "total_revenue"
  sql = "sum(price * quantity)"

  [[block.measures]]
  name = "total_count"
  sql = "count(*)"

  [[block.measures]]
  name = "total_products"
  sql = "count(product)"